name: "Load Prices NAS into DB"

on:
  workflow_dispatch:
  schedule:
    # run once a month
    - cron: "0 1 1 * *"

jobs:
  load:
    if: github.repository == 'adagrad/findb'
    runs-on: ubuntu-latest
    env:
      RELEASE: 2021
      FIN_DB: fin.db
      # Note we need to repeat this value in the upload step because of:
      #  https://github.com/meeDamian/github-release/issues/22
      PRC_DB: yfp_NAS.db
      XE: NAS
    steps:
      - name: Set current year as env
        id: year
        run: echo "::set-output name=year::$(date +'%Y')"
      #
      #   only one concurrent run allowed!!!
      #
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #
      #   checkout
      #
      - name: checkout repository
        uses: actions/checkout@v2
      #
      #   python
      #
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          sudo apt-get install dateutils sqlite3
          python -m pip install --upgrade pip setuptools
          python -m pip install -r requirements.txt
      #
      #   action, fetch database
      #
      - name: fetch and extract database
        run: |
          echo "current year: $YEAR"
          python findb/utils/github_asset.py GET ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} "$RELEASE" "$FIN_DB.tgz" "$PRC_DB.tgz"
          pwd
          ls -lh
          tar -xzf "$FIN_DB.tgz"
          tar -xzf "$PRC_DB".tgz
          ls -lh
      #
      #   action, load csv files
      #
      - name: append sqlite database
        continue-on-error: true
        run: |
          sqlite3 $PRC_DB < findb/data/.ddl/yfp.sql
          python findb/get_yf_prices.py -s "$FIN_DB" -d "$PRC_DB" -x $XE -b `dateutils.dadd today -2mo` -e `dateutils.dadd today +0d` -a -t 300
          ls -l
          tar -czf "$PRC_DB.tgz" "$PRC_DB"
          python findb/utils/github_asset.py PUT ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} "$RELEASE" "$PRC_DB.tgz"
