name: "Load CSV into DB"

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  load:
    if: github.repository == 'adagrad/findb'
    runs-on: ubuntu-latest
    env:
      RELEASE: 2021
    steps:
      #
      #   only one concurrent run allowed!!!
      #
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #
      #   checkout
      #
      - name: checkout repository
        uses: actions/checkout@v2
      #
      #   python
      #
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          sudo apt-get install sqlite3
          python -m pip install --upgrade pip setuptools
          python -m pip install -r requirements.txt
      #
      #   action, fetch database
      #
      - name: fetch and extract database
        run: |
          python findb/utils/fetch_github_asset.py ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} "$RELEASE" fin.db.tgz
          pwd
          ls -lh
          tar -xzf fin.db.tgz || true
          ls -lh
      #
      #   action, load csv files
      #
      - name: append sqlite database
        run: |
          sqlite3 fin.db < findb/data/.ddl/static.sql
          python findb/utils/csv_to_sqlite.py -f findb/data/yahoo_symbols.csv -d fin.db -t yf_symbol
          python findb/utils/csv_to_sqlite.py -f findb/data/yahoo_info.csv* -d fin.db -t yf_info
          python findb/utils/csv_to_sqlite.py -f findb/data/ib_symbols.csv -d fin.db -t ib_symbol
          python findb/utils/csv_to_sqlite.py -f findb/data/ib_fractional.csv -d fin.db -t ib_fractional
          python findb/utils/csv_to_sqlite.py -f findb/data/optionable.csv -d fin.db -t optionable
      #
      #   update release asset
      #
      - uses: meeDamian/github-release@2.0
        name: upload database
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_override: true
          files: fin.db
          draft: false
          gzip: true
          name: db
          tag: db
