name: "test"

on:
  workflow_dispatch:

jobs:
  check:
    if: github.repository == 'KIC/quantdb'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: echo
        run: |
          echo ${{ github.repository }}

