name: "test"

on:
  workflow_dispatch:

jobs:
  check:
    if: github.repository == 'adagrad/findb'
    runs-on: ubuntu-latest
    steps:
      #
      #   checkout
      #
      - name: chckout repository
        uses: actions/checkout@v2
      #
      #   action
      #
      - name: test
        run: echo "foo,bar" >> findb/data/.test.csv
      #
      #   commit changes
      #
      - uses: EndBug/add-and-commit@v7
        name: commit changes
        with:
          add: findb/data/
          author_name: action
          author_email: action@github.com
          # push: false
