name: "test"

on:
  workflow_dispatch:

jobs:
  check:
    if: github.repository == 'adagrad/findb'
    runs-on: ubuntu-latest
    env:
      # Note we need to repeat this value in the upload step because of:
      #  https://github.com/meeDamian/github-release/issues/22
      FILE: findb/data/.test.csv
    steps:
      #
      #   checkout
      #
      - name: chckout repository
        uses: actions/checkout@v2
      #
      #   action
      #
      - name: test
        run: echo "foo,bar" >> $FILE
      #
      #   commit changes
      #
      - uses: EndBug/add-and-commit@v7
        name: commit changes
        with:
          add: findb/data/
          author_name: action
          author_email: action@github.com
          # push: false
      - uses: meeDamian/github-release@2.0
        name: upload file
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_override: true
          #files: ${{ env.FILE }}
          files: findb/data/.test.csv
          gzip: false
          tag: db
